"""empty message

Revision ID: 97ce805e5e4d
Revises: dcecaaf2ef4f
Create Date: 2020-11-09 19:35:15.584519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ce805e5e4d'
down_revision = 'dcecaaf2ef4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('phone_number', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'phone_number')
    # ### end Alembic commands ###
